#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"
import { categories, contentRules, entropyRule, largeFileRule, riskyFileRules, severityRank } from "../src/rules.js"

const projectRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const documentPath = path.join(projectRoot, "docs", "RULES.md")

const detection = rule => {
  if (riskyFileRules.includes(rule)) return "File path pattern"
  if (rule.id === entropyRule.id) return "Content analysis"
  if (rule.id === largeFileRule.id) return "File size"
  return "Content pattern"
}

const guidance = {
  // shareguard-ignore-next-line generic-secret
  secret: "Remove the value from the file, rotate it with its provider, then store it in an environment variable or a secret manager.",
  privacy: "Remove or replace the personal data with a placeholder before sharing the file, or scope it to a narrow `allow` entry when it is intentional public contact information.",
  hygiene: "Delete the file, add it to `.gitignore`, or move the artifact outside the shared folder."
}

const ordered = [...contentRules, ...riskyFileRules, entropyRule, largeFileRule]
  .slice()
  .sort((first, second) => severityRank[second.severity] - severityRank[first.severity] || first.id.localeCompare(second.id))

export const renderRules = () => {
  const lines = [
    "# ShareGuard rule reference",
    "",
    "Generated by `npm run docs`. Edit `src/rules.js` and regenerate instead of editing this file.",
    "",
    `ShareGuard ships ${ordered.length} rules across ${categories.length} categories. Every finding reports a file, an optional line, a rule identifier, and a severity. Matched values are never included in any output format.`,
    "",
    "Disable a rule for one scan with `--exclude-rule <id>`, restrict a scan with `--include-rule <id>` or `--category <name>`, approve a reviewed finding with an `allow` entry in `.shareguard.json`, or skip a single line with a `shareguard-ignore-line <id>` comment.",
    ""
  ]

  for (const category of categories) {
    const rules = ordered.filter(rule => rule.category === category)
    lines.push(`## ${category}`, "", guidance[category], "", "| Rule | Severity | Detection | Description |", "| --- | --- | --- | --- |")
    for (const rule of rules) lines.push(`| [\`${rule.id}\`](#${rule.id}) | ${rule.severity} | ${detection(rule)} | ${rule.description} |`)
    lines.push("")
  }

  lines.push("## Rule details", "")
  for (const rule of ordered) {
    lines.push(
      `### ${rule.id}`,
      "",
      `- Category: \`${rule.category}\``,
      `- Severity: \`${rule.severity}\``,
      `- Detection: ${detection(rule)}`,
      `- Description: ${rule.description}`,
      `- Resolution: ${guidance[rule.category]}`,
      ""
    )
  }

  lines.push("Severity thresholds are compared with `--fail-on low|medium|high|critical|none`.", "")
  return lines.join("\n")
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
  const document = renderRules()
  const current = await readFile(documentPath, "utf8").catch(() => null)

  if (process.argv.includes("--check")) {
    if (current === document) {
      process.stdout.write("docs/RULES.md is up to date\n")
    } else {
      process.stderr.write("docs/RULES.md is out of date; run npm run docs\n")
      process.exitCode = 1
    }
  } else if (current === document) {
    process.stdout.write("docs/RULES.md is already up to date\n")
  } else {
    await writeFile(documentPath, document, "utf8")
    process.stdout.write(`wrote docs/RULES.md\n`)
  }
}
